-- MySQL Script generated by MySQL Workbench
-- Sun Jun 27 19:08:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema facturacion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema facturacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `facturacion` DEFAULT CHARACTER SET utf8 ;
USE `facturacion` ;

-- -----------------------------------------------------
-- Table `facturacion`.`Categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `facturacion`.`Categorias` ;

CREATE TABLE IF NOT EXISTS `facturacion`.`Categorias` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facturacion`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `facturacion`.`Productos` ;

CREATE TABLE IF NOT EXISTS `facturacion`.`Productos` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `descProducto` VARCHAR(45) NULL,
  `precio` DECIMAL(12,2) NULL,
  `stock` INT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Producto_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `facturacion`.`Categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facturacion`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `facturacion`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `facturacion`.`Clientes` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facturacion`.`Modos_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `facturacion`.`Modos_pago` ;

CREATE TABLE IF NOT EXISTS `facturacion`.`Modos_pago` (
  `idModo_pago` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idModo_pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facturacion`.`Facturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `facturacion`.`Facturas` ;

CREATE TABLE IF NOT EXISTS `facturacion`.`Facturas` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `Cliente_idCliente` INT NOT NULL,
  `fecha` DATETIME NULL,
  `Modo_pago_idModo_pago` INT NOT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `fk_Factura_Cliente_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Factura_Modo_pago1_idx` (`Modo_pago_idModo_pago` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `facturacion`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Modo_pago1`
    FOREIGN KEY (`Modo_pago_idModo_pago`)
    REFERENCES `facturacion`.`Modos_pago` (`idModo_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facturacion`.`Detalles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `facturacion`.`Detalles` ;

CREATE TABLE IF NOT EXISTS `facturacion`.`Detalles` (
  `idDetalle` INT NOT NULL AUTO_INCREMENT,
  `Factura_idFactura` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `cantidad` INT NULL,
  `precio` DECIMAL(12,2) NULL,
  PRIMARY KEY (`idDetalle`),
  INDEX `fk_Detalle_Factura1_idx` (`Factura_idFactura` ASC) VISIBLE,
  INDEX `fk_Detalle_Producto1_idx` (`Producto_idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Detalle_Factura1`
    FOREIGN KEY (`Factura_idFactura`)
    REFERENCES `facturacion`.`Facturas` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `facturacion`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
